algoritmo "07-enquanto-faca"
// Função : Estrutura de Repetição Enquanto
// Autor  : Edson Maia

var
    x, y : inteiro // contador do laço

inicio

    x <- 1 // inicializar a variável

// ENQUANTO condicao for Verdadeira FAÇA
// escrever do 1 até o 10
enquanto x <= 10 faca
    escreval(x)
    x <- x + 1 // incremento x++
fimenquanto

    y <- 7 // inicializar a variável

// escrever do 7 até o 1
enquanto y > 0 faca
    escreval(y)
    y <- y - 1 // decremento y--
fimenquanto

fimalgoritmo
